### ISSUE TITLE
ERROR: No matching distribution found for anticaptchaofficial

### ISSUE THREAD

**Issue by BarryThrill** [AdminAnticaptcha/anticaptcha-python#1]
Python 3.7

>>> pip install anticaptchaofficial

ERROR: Could not find a version that satisfies the requirement anticaptchaofficial (from versions: none)
ERROR: No matching distribution found for anticaptchaofficial

**Comment by rivalfpv** [comment]
same on 3.7.3

**Comment by AdminAnticaptcha** [comment]
Hi, please try again, should be working

**Comment by rivalfpv** [comment]
> Hi, please try again, should be working

its ok now
