### ISSUE TITLE
Does it work for this case?

### ISSUE THREAD

**Issue by thiagoveloso** [AdminAnticaptcha/anticaptcha-python#11]
I am trying to download agricultural census data for 5595 municipalities. Unfortunately, the government agency publishing the data forces the user to solve a captcha for every file to be downloaded. This is the main website where the data are located:

https://www.car.gov.br/publico/municipios/downloads?sigla=MG

At this page, one needs to go through each municipality name, click the globe icon and solve the captcha, which leads to rather simple URL like this one:

https://www.car.gov.br/publico/municipios/shapefile?municipio%5Bid%5D=3100104&email=abc%40xyz.com&captcha=pKYuB

where `3100104` is the geocode of the municipality and `pKYuB` is the solved captcha.

Since I have a list of all geocodes I need, I can easily iterate over all of them and assemble a url for each one. I am even considering to purchase AC to build a robot that will help downloading all files I need.

**However, my question is: given the sample download url provided above, how can I programmatically "trigger" a new captcha for each geocode, so I can send it to the Anti-captcha API to solve it?**

At the page containing the captcha, this is what I get when I copy the captcha's image address:

`https://www.car.gov.br/publico/municipios/captcha?id=656825`.

This is the source code of the website at the captcha request:

```
<div class="form-group">
						
						<div class="text-center">
							<img id="img-captcha-base-downloads" src="../municipios/captcha">
							<button id="btn-atualizar-captcha" class="btn btn-sm btn-info" title="Clique para gerar outra imagem">
								<span class="fa fa-refresh"></span>
							</button>
						</div>
						<label>Digite os caracteres da imagem acima (diferenciando maiúsculas de minúsculas):</label>
						<input type="text" id="form-captcha-download-base" class="form-control">

					</div>

```
The `../municipios/captcha` excerpt leads to this page: https://www.car.gov.br/publico/municipios/captcha .

**Comment by AdminAnticaptcha** [comment]
This issue is not a problem of our service. We don't help in breaking websites, we only solve captchas.
