### ISSUE TITLE
Is it possible to disable python prints on anti-captcha when solving a task

### ISSUE THREAD

**Issue by samuelcarrarap** [AdminAnticaptcha/anticaptcha-python#15]
Is it possible to disable python prints on anti-captcha when solving a task?

These are the logs I'm getting --->

making request to createTask
created task with id XXXXXXX
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task solved

**Comment by AdminAnticaptcha** [comment]
Use set_verbose(0):

solver.set_verbose(0)
