### ISSUE TITLE
python 3 wrong syntax

### ISSUE THREAD

**Issue by rivalfpv** [AdminAnticaptcha/anticaptcha-python#2]
Cannot import 'anticaptchaofficial.antinetworking' due to syntax error "Missing parentheses in call to 'print'. Did you mean print(msg)? (<unknown>, line 150)"

**Comment by galfaroth** [comment]
Having the same problem on OSX Python 3.7.6

**Comment by galfaroth** [comment]
Thus can't use the library:
/env/lib/python3.7/site-packages/anticaptchaofficial/recaptchav2proxyless.py", line 1, in <module>
    from antinetworking import *
ModuleNotFoundError: No module named 'antinetworking'

**Comment by AdminAnticaptcha** [comment]
`pip3 uninstall anticaptchaofficial
pip3 intall anticaptchaofficial`

Should be working with python3 now, dropped support for python2
