### ISSUE TITLE
reporting incorrect captcha

### ISSUE THREAD

**Issue by aflaldf** [AdminAnticaptcha/anticaptcha-python#21]
```
  solver.report_incorrect_image_captcha()
AttributeError: 'imagecaptcha' object has no attribute 'report_incorrect_image_captcha'
```

Cannot report incorrect image captcha in this way.  Please help

**Comment by AdminAnticaptcha** [comment]
Did you import ?
from anticaptchaofficial.antinetworking import *

**Comment by aflaldf** [comment]
would that be enough? wont we need an antinetworking object to use that function and how would it be connected to the imagecaptcha task? Could you please show how to do this?

**Comment by AdminAnticaptcha** [comment]
It's all in the source code. My time cost $$$ if you're ready to pay $500/hour.
