### ISSUE TITLE
Unable to report incorrect image captcha (getting No such captcha id)

### ISSUE THREAD

**Issue by aflaldf** [AdminAnticaptcha/anticaptcha-python#22]
```
making request to reportIncorrectImageCaptcha
{'errorId': 16, 'errorCode': 'ERROR_NO_SUCH_CAPCHA_ID', 'errorDescription': 'Task you are requesting does not exist in your current task list or has been expired. Could not find appropriate task, make sure it had no errors and you have not reported it yet.'}
```
getting this when trying to report image captcha incorrect even I am reporting this before 60 seconds

**Comment by AdminAnticaptcha** [comment]
Do you complain on captcha with Russian symbols?

**Comment by aflaldf** [comment]
No russian symbols

**Comment by brusenskiy** [comment]
> Do you complain on captcha with Russian symbols?

Yeah, got the same error with cyrillic.

Call `report_incorrect_image()` for created job object right after getting incorrect result.
