### ISSUE TITLE
How to add Blob Data FunCaptcha

### ISSUE THREAD

**Issue by Pr0t0ns** [AdminAnticaptcha/anticaptcha-python#24]
I have been trying to figure out a way to insert blob data
your docs say it works like this
# solver.set_data_blob("{\"blob\":\"DATA_BLOB_VALUE_HERE\"}")
But I have to way of inserting the blob data variable in their with those backslashes

**Comment by AdminAnticaptcha** [comment]
You should escape quotes.
`solver.set_data_blob("{\"blob\":\"DATA_BLOB_VALUE_HERE\"}")`
