### ISSUE TITLE
precaching for recaptcha V2

### ISSUE THREAD

**Issue by shn91** [AdminAnticaptcha/anticaptcha-python#25]
Hello,
![Capture](https://user-images.githubusercontent.com/112544410/188282495-9c2d083d-3b4c-4f34-a09c-ac389f9fbda1.JPG)

when I use AntiCaptcha by extension in the advanced setting, a Use Recaptcha preaching up to 10 degrees we have faster-solving recaptchas than simple. How to use this feature with python code?

**Comment by AdminAnticaptcha** [comment]
Not a library issue

**Comment by shn91** [comment]
> Not a library issue
Please guide me on how to fix this problem.
