### ISSUE TITLE
Anti-Captcha API not working with web application which requires authentication

### ISSUE THREAD

**Issue by AdlanKadri** [AdminAnticaptcha/anticaptcha-python#26]
we have integrated the **`anti-captcha API`** to Bypass the **`recaptcha V2`** on an application that requires **authentication** (user-password), the API manages to return a **TOKEN**, but this **TOKEN** does not work on the page.
we tested the same thing on a DEMO page, and it works.

- Is it because we are on a web application with authentication? is there a way to handle this?

**Comment by AdminAnticaptcha** [comment]
No we don't need authentication, we never visit actual page but a clone of it instead. I suggest you to dig deeper in browser emulation. Closing issue, not related to the package.
