### ISSUE TITLE
Help how to solve this?

### ISSUE THREAD

**Issue by rizalPro2** [AdminAnticaptcha/anticaptcha-python#27]
hello, how to solve if thrs a pop up like this? already use ur service, but everytime click submit always showing pop up like this. can anticapctha help me how to solve this? thats make my credit gone for nothing. :(
![test](https://user-images.githubusercontent.com/116349523/197183505-91930a4b-0c31-46e2-86ad-4056bbaa9858.png)

**Comment by AdminAnticaptcha** [comment]
Not related to library itself. Post tickets.
