### ISSUE TITLE
API error ERROR_INCORRECT_SESSION_DATA: Some of the required values for successive user emulation are missing

### ISSUE THREAD

**Issue by alankar01** [AdminAnticaptcha/anticaptcha-python#29]
I am getting a session data error, I have done everything same as the documentation and I can't able to figure out the error.

Code:-

solver = recaptchaV2Proxyless()
                solver.set_verbose(1)
                solver.set_key('****')
                print(type(driver.current_url))
                solver.set_website_url(url)
                solver.set_website_key(sitekey)
                solver.set_soft_id(0)

                g_response = solver.solve_and_return_solution()
                if g_response != 0:
                    print("g-response: "+g_response)
                else:
                    print("task finished with error "+solver.error_code)

response:- 
could not create task
API error ERROR_INCORRECT_SESSION_DATA: Some of the required values for successive user emulation are missing. Website key 
'<div class="g-recaptcha" data-sitekey="6Le9awYTAAAAAG5BwvKpBAw5u-f5ZF92-GEyeO3F" data-callback="captchaCallback"><div style="width: 304px; height: 78px;"><div><iframe title="reCAPTCHA" src="https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Le9awYTAAAAAG5BwvKpBAw5u-f5ZF92-GEyeO3F&amp;co=aHR0cHM6Ly9lcGFwZXIuZmluYW5jaWFsZXhwcmVzcy5jb206NDQz&amp;hl=en&amp;v=Km9gKuG06He-isPsP6saG8cn&amp;size=normal&amp;cb=2ntjf0w71ia6" width="304" height="78" role="presentation" name="a-phf3o2lv2u2t" 
frameborder="0" scrolling="no" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox"></iframe></div><textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid rgb(193, 193, 193); margin: 10px 25px; padding: 0px; resize: none; display: none;"></textarea></div><iframe style="display: none;"></iframe></div>' is invalid.
task finished with error ERROR_INCORRECT_SESSION_DATA

**Comment by AdminAnticaptcha** [comment]
You are sending empty sitekey value.

**Comment by AdminAnticaptcha** [comment]
You're sending sitekey value which is some HTML code with iframe. See docs for what it should be like.
