### ISSUE TITLE
Error not returned and can't figure what went wrong

### ISSUE THREAD

**Issue by ExLineP** [AdminAnticaptcha/anticaptcha-python#33]
Having issue with script that needs to work non-stop but returns error after 2-3 hours which looks like this:

**making request to createTask
created task with id 444016857
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
task is still processing
making request to getTaskResult
Traceback (most recent call last):
  File "F:\Projects\turkey_bank\login.py", line 102, in login
    checkForBan(driver, count, proxy_count)**

What went wrong and how can I maybe reduce number of requests and proceed to next captcha if this one couldn't be done?

**Comment by Technetium1** [comment]
Run in debugger and see the last invalid value to cause the traceback

**Comment by AdminAnticaptcha** [comment]
put a try-catch block to see what's wrong
