### ISSUE TITLE
How do i get a site key

### ISSUE THREAD

**Issue by johnny777857** [AdminAnticaptcha/anticaptcha-python#8]

**Comment by erikKeresztes** [comment]
siteKey = re.search(r'&k=(.*?)&', driver.find_element_by_css_selector("iframe[role='presentation']").get_attribute('src')).group()

**Comment by erikKeresztes** [comment]
That is, if you're using Selenium

**Comment by huyhoang55hm** [comment]
how to get sitekey

**Comment by rajasaad7** [comment]
go to the developer's tool and in the HTML code look for the div where captcha is placed and then press crtl+f and type "site" and look for site key variable

**Comment by mikegrep** [comment]
> siteKey = re.search(r'&k=(.*?)&', driver.find_element_by_css_selector("iframe[role='presentation']").get_attribute('src')).group()

I foun it anyway but what to do with g-response code after reciven it

**Comment by AdminAnticaptcha** [comment]
We have [tutorials](https://anti-captcha.com/tutorials) where you can learn how to find Recaptcha sitekey.
